### Sequence Classification Problem

In [35]:
# Import libraries
import numpy as np
import pandas as pd
from random import random
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, TimeDistributed, LSTM

In [9]:
# create a sequence of random numbers in [0,1]
X = np.array([random() for _ in range(10)])

In [11]:
print(X)

[0.7699529  0.98369393 0.83465591 0.07482834 0.9086333  0.90410979
 0.58070424 0.82828898 0.58467159 0.78239139]


In [12]:
# calculate cut-off value to change class values
limit = 10/4.0

In [13]:
limit

2.5

In [22]:
# determine the class outcome for each item in cumulative sequence
# example : pos1, pos1+pos2, pos1+pos2+pos3, ...
y = np.array([0 if x < limit else 1 for x in np.cumsum(X)])

In [19]:
0.7699529 + 0.98369393

1.75364683

In [23]:
y

array([0, 0, 1, 1, 1, 1, 1, 1, 1, 1])

In [31]:
def get_sequence(n_timesteps):
    # create a sequence of random numbers in [0,1]
    X = np.array([random() for _ in range(n_timesteps)])
    
    # calculate cut-off value to change class values
    limit = n_timesteps/4.0
    
    # determine the class outcome for each item in cumulative sequence
    y = np.array([0 if x < limit else 1 for x in np.cumsum(X)])
    
    # reshape input and output data to be suitable for LSTMs
    X = X.reshape(1, n_timesteps, 1)
    y = y.reshape(1, n_timesteps, 1)
    return X, y

In [32]:
X, y = get_sequence(10)
print(X)
print(y)

[[[0.81401964]
  [0.35913542]
  [0.00972609]
  [0.25226574]
  [0.88856426]
  [0.8108807 ]
  [0.46740304]
  [0.13033457]
  [0.6930286 ]
  [0.72078823]]]
[[[0]
  [0]
  [0]
  [0]
  [0]
  [1]
  [1]
  [1]
  [1]
  [1]]]


In [38]:
# define problem properties
n_timesteps = 10

In [36]:
# define LSTM
model = Sequential()
model.add(LSTM(20, input_shape=(10, 1), return_sequences=True))
model.add(TimeDistributed(Dense(1, activation='sigmoid')))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [39]:
# train LSTM
for epoch in range(1000):
    # generate new random sequence
    X,y = get_sequence(n_timesteps)
    # fit model for one epoch on this sequence
    model.fit(X, y, epochs=1, batch_size=1, verbose=2)

1/1 - 2s - loss: 0.6903 - accuracy: 0.7000
1/1 - 0s - loss: 0.7146 - accuracy: 0.3000
1/1 - 0s - loss: 0.6877 - accuracy: 0.7000
1/1 - 0s - loss: 0.6997 - accuracy: 0.4000
1/1 - 0s - loss: 0.7109 - accuracy: 0.3000
1/1 - 0s - loss: 0.6993 - accuracy: 0.5000
1/1 - 0s - loss: 0.6936 - accuracy: 0.4000
1/1 - 0s - loss: 0.6955 - accuracy: 0.3000
1/1 - 0s - loss: 0.6928 - accuracy: 0.5000
1/1 - 0s - loss: 0.6896 - accuracy: 0.7000
1/1 - 0s - loss: 0.6898 - accuracy: 0.7000
1/1 - 0s - loss: 0.6883 - accuracy: 0.7000
1/1 - 0s - loss: 0.6852 - accuracy: 0.9000
1/1 - 0s - loss: 0.6856 - accuracy: 0.7000
1/1 - 0s - loss: 0.6959 - accuracy: 0.3000
1/1 - 0s - loss: 0.6795 - accuracy: 1.0000
1/1 - 0s - loss: 0.6831 - accuracy: 0.7000
1/1 - 0s - loss: 0.6911 - accuracy: 0.4000
1/1 - 0s - loss: 0.6859 - accuracy: 0.7000
1/1 - 0s - loss: 0.6642 - accuracy: 0.9000
1/1 - 0s - loss: 0.6690 - accuracy: 0.8000
1/1 - 0s - loss: 0.6710 - accuracy: 0.7000
1/1 - 0s - loss: 0.6844 - accuracy: 0.4000
1/1 - 0s - 

1/1 - 0s - loss: 1.0100 - accuracy: 0.6000
1/1 - 0s - loss: 0.2704 - accuracy: 1.0000
1/1 - 0s - loss: 0.2982 - accuracy: 0.9000
1/1 - 0s - loss: 0.3141 - accuracy: 0.9000
1/1 - 0s - loss: 0.3116 - accuracy: 1.0000
1/1 - 0s - loss: 0.2988 - accuracy: 0.9000
1/1 - 0s - loss: 0.3297 - accuracy: 0.9000
1/1 - 0s - loss: 0.3486 - accuracy: 0.9000
1/1 - 0s - loss: 0.2803 - accuracy: 1.0000
1/1 - 0s - loss: 0.3447 - accuracy: 0.9000
1/1 - 0s - loss: 0.4766 - accuracy: 0.8000
1/1 - 0s - loss: 0.3030 - accuracy: 0.9000
1/1 - 0s - loss: 0.4082 - accuracy: 0.8000
1/1 - 0s - loss: 0.5134 - accuracy: 0.8000
1/1 - 0s - loss: 0.2895 - accuracy: 1.0000
1/1 - 0s - loss: 0.3909 - accuracy: 0.9000
1/1 - 0s - loss: 0.4620 - accuracy: 0.8000
1/1 - 0s - loss: 0.3058 - accuracy: 1.0000
1/1 - 0s - loss: 0.3223 - accuracy: 0.9000
1/1 - 0s - loss: 0.3117 - accuracy: 0.9000
1/1 - 0s - loss: 0.2712 - accuracy: 1.0000
1/1 - 0s - loss: 0.3318 - accuracy: 1.0000
1/1 - 0s - loss: 0.4356 - accuracy: 0.9000
1/1 - 0s - 

1/1 - 0s - loss: 0.2285 - accuracy: 0.9000
1/1 - 0s - loss: 0.3515 - accuracy: 0.9000
1/1 - 0s - loss: 0.4318 - accuracy: 0.9000
1/1 - 0s - loss: 0.2979 - accuracy: 0.9000
1/1 - 0s - loss: 0.2403 - accuracy: 0.9000
1/1 - 0s - loss: 0.2898 - accuracy: 0.9000
1/1 - 0s - loss: 0.2274 - accuracy: 0.9000
1/1 - 0s - loss: 0.2123 - accuracy: 1.0000
1/1 - 0s - loss: 0.1959 - accuracy: 1.0000
1/1 - 0s - loss: 1.8597 - accuracy: 0.5000
1/1 - 0s - loss: 0.2464 - accuracy: 0.9000
1/1 - 0s - loss: 0.2135 - accuracy: 1.0000
1/1 - 0s - loss: 0.2325 - accuracy: 1.0000
1/1 - 0s - loss: 0.3130 - accuracy: 0.9000
1/1 - 0s - loss: 0.3371 - accuracy: 0.9000
1/1 - 0s - loss: 0.3057 - accuracy: 0.9000
1/1 - 0s - loss: 0.2637 - accuracy: 0.9000
1/1 - 0s - loss: 0.2100 - accuracy: 0.9000
1/1 - 0s - loss: 0.2076 - accuracy: 1.0000
1/1 - 0s - loss: 0.2028 - accuracy: 0.9000
1/1 - 0s - loss: 0.2121 - accuracy: 1.0000
1/1 - 0s - loss: 0.3318 - accuracy: 0.9000
1/1 - 0s - loss: 0.1838 - accuracy: 1.0000
1/1 - 0s - 

1/1 - 0s - loss: 0.1573 - accuracy: 0.9000
1/1 - 0s - loss: 1.3798 - accuracy: 0.6000
1/1 - 0s - loss: 0.1844 - accuracy: 0.9000
1/1 - 0s - loss: 0.1938 - accuracy: 1.0000
1/1 - 0s - loss: 0.2962 - accuracy: 0.9000
1/1 - 0s - loss: 0.1954 - accuracy: 1.0000
1/1 - 0s - loss: 0.1704 - accuracy: 1.0000
1/1 - 0s - loss: 0.2139 - accuracy: 0.9000
1/1 - 0s - loss: 0.2269 - accuracy: 0.9000
1/1 - 0s - loss: 0.2398 - accuracy: 0.9000
1/1 - 0s - loss: 0.4589 - accuracy: 0.8000
1/1 - 0s - loss: 0.1627 - accuracy: 0.9000
1/1 - 0s - loss: 0.1976 - accuracy: 0.9000
1/1 - 0s - loss: 0.9305 - accuracy: 0.7000
1/1 - 0s - loss: 0.2944 - accuracy: 0.9000
1/1 - 0s - loss: 0.1882 - accuracy: 1.0000
1/1 - 0s - loss: 0.2547 - accuracy: 0.9000
1/1 - 0s - loss: 0.1634 - accuracy: 1.0000
1/1 - 0s - loss: 0.1671 - accuracy: 1.0000
1/1 - 0s - loss: 0.1714 - accuracy: 1.0000
1/1 - 0s - loss: 0.1872 - accuracy: 1.0000
1/1 - 0s - loss: 0.1617 - accuracy: 1.0000
1/1 - 0s - loss: 0.2193 - accuracy: 0.9000
1/1 - 0s - 

1/1 - 0s - loss: 0.1646 - accuracy: 0.9000
1/1 - 0s - loss: 0.1404 - accuracy: 1.0000
1/1 - 0s - loss: 0.1122 - accuracy: 1.0000
1/1 - 0s - loss: 0.1228 - accuracy: 1.0000
1/1 - 0s - loss: 0.2085 - accuracy: 0.9000
1/1 - 0s - loss: 0.1576 - accuracy: 0.9000
1/1 - 0s - loss: 0.1614 - accuracy: 0.9000
1/1 - 0s - loss: 0.1411 - accuracy: 1.0000
1/1 - 0s - loss: 0.1382 - accuracy: 1.0000
1/1 - 0s - loss: 0.1364 - accuracy: 0.9000
1/1 - 0s - loss: 0.1611 - accuracy: 0.9000
1/1 - 0s - loss: 0.1110 - accuracy: 1.0000
1/1 - 0s - loss: 0.4316 - accuracy: 0.8000
1/1 - 0s - loss: 0.1342 - accuracy: 0.9000
1/1 - 0s - loss: 0.1832 - accuracy: 0.9000
1/1 - 0s - loss: 0.2564 - accuracy: 0.9000
1/1 - 0s - loss: 0.1853 - accuracy: 0.9000
1/1 - 0s - loss: 0.1189 - accuracy: 1.0000
1/1 - 0s - loss: 0.1144 - accuracy: 1.0000
1/1 - 0s - loss: 0.1615 - accuracy: 0.9000
1/1 - 0s - loss: 0.1649 - accuracy: 0.9000
1/1 - 0s - loss: 0.1950 - accuracy: 0.9000
1/1 - 0s - loss: 0.1750 - accuracy: 0.9000
1/1 - 0s - 

1/1 - 0s - loss: 0.2784 - accuracy: 0.9000
1/1 - 0s - loss: 0.1083 - accuracy: 1.0000
1/1 - 0s - loss: 0.1367 - accuracy: 1.0000
1/1 - 0s - loss: 0.1838 - accuracy: 0.9000
1/1 - 0s - loss: 0.2321 - accuracy: 0.9000
1/1 - 0s - loss: 0.1314 - accuracy: 1.0000
1/1 - 0s - loss: 0.1283 - accuracy: 1.0000
1/1 - 0s - loss: 0.1158 - accuracy: 1.0000
1/1 - 0s - loss: 0.1906 - accuracy: 0.9000
1/1 - 0s - loss: 0.1094 - accuracy: 1.0000
1/1 - 0s - loss: 0.2922 - accuracy: 0.9000
1/1 - 0s - loss: 0.1024 - accuracy: 1.0000
1/1 - 0s - loss: 0.2109 - accuracy: 0.9000
1/1 - 0s - loss: 0.1378 - accuracy: 1.0000
1/1 - 0s - loss: 0.1094 - accuracy: 1.0000
1/1 - 0s - loss: 0.1084 - accuracy: 1.0000
1/1 - 0s - loss: 0.1993 - accuracy: 0.9000
1/1 - 0s - loss: 0.2703 - accuracy: 0.9000
1/1 - 0s - loss: 0.2424 - accuracy: 0.9000
1/1 - 0s - loss: 0.1148 - accuracy: 1.0000
1/1 - 0s - loss: 0.1639 - accuracy: 0.9000
1/1 - 0s - loss: 0.1341 - accuracy: 0.9000
1/1 - 0s - loss: 0.1033 - accuracy: 1.0000
1/1 - 0s - 

In [40]:
# evaluate LSTM
X,y = get_sequence(n_timesteps)

In [44]:
yhat = model.predict(X, verbose=0)

In [45]:
for i in range(n_timesteps):
    print('Expected:', y[0, i], 'Predicted', yhat[0, i])

Expected: [0] Predicted [0.16332197]
Expected: [0] Predicted [0.10287166]
Expected: [0] Predicted [0.06966642]
Expected: [0] Predicted [0.14985427]
Expected: [1] Predicted [0.5066353]
Expected: [1] Predicted [0.9217285]
Expected: [1] Predicted [0.9865296]
Expected: [1] Predicted [0.99400973]
Expected: [1] Predicted [0.9954481]
Expected: [1] Predicted [0.99539423]
